include: package:lint/analysis_options.yaml

analyzer:
  errors:
    missing_return: error
    missing_required_param: error
    must_be_immutable: error
    depend_on_referenced_packages: ignore
    invalid_assignment: ignore
    avoid_classes_with_only_static_members: ignore
    avoid_bool_literals_in_conditional_expressions: ignore
    unnecessary_overrides: ignore
    avoid_void_async: ignore
    avoid_positional_boolean_parameters: ignore
    argument_type_not_assignable: ignore
    use_build_context_synchronously: ignore
    require_trailing_commas: ignore