name: rentop
description: car rental marketplace in UAE.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.18.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_svg: ^1.1.6
  flutter_native_splash: ^2.2.16
  getwidget: ^3.0.1
  freezed_annotation: ^2.2.0
  dartz: ^0.10.1
  go_router: ^6.0.0

dev_dependencies:
  build_runner: ^2.3.3
  flutter_lints: ^2.0.0
  freezed: ^2.3.2

flutter:
  
  uses-material-design: true

  assets:
    - assets/images/logo/
    - assets/images/icons/
    - assets/images/images/

  fonts:
    - family: Comfortaa
      fonts:
        - asset: assets/fonts/Comfortaa.ttf

flutter_native_splash:
  color: "#FFFFFF"
  image: assets/images/logo/logo.png
  android: true
  ios: true