name: rentop
description: car rental marketplace in UAE.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.18.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_svg: ^1.1.6
  getwidget: ^3.0.1
  freezed_annotation: ^2.2.0
  dartz: ^0.10.1
  injectable: ^2.1.0
  flutter_dotenv: ^5.0.2
  http: ^0.13.5
  flutter_bloc: ^7.3.3
  get_it: ^7.2.0
  shared_preferences: ^2.0.15
  another_flushbar: ^1.12.29
  carousel_slider: ^4.2.1
  favorite_button: ^0.0.4
  animation_wrappers: ^3.0.0
  pull_to_refresh: ^2.0.0
  google_maps_flutter: ^2.2.3
  intl: ^0.18.0
  font_awesome_flutter: ^10.4.0
  dropdown_button2: ^1.9.2
  syncfusion_flutter_datepicker: ^20.4.51

dependency_overrides:
  font_awesome_flutter:
    path: assets/packages/font_awesome_flutter

dev_dependencies:
  build_runner: ^2.3.3
  freezed: ^2.3.2
  injectable_generator: ^2.1.3
  lint: ^2.0.1

flutter:
  
  uses-material-design: true

  assets:
    - assets/images/logo/
    - assets/images/icons/
    - assets/images/icons/car_features/
    - assets/images/icons/auto/
    - assets/images/icons/car_brands/
    - assets/images/icons/car_categories/
    - assets/images/images/
    - .env

  fonts:
    - family: Comfortaa
      fonts:
        - asset: assets/fonts/Comfortaa.ttf