name: rentop
version: 1.0.0+1
publish_to: none
description: car rental marketplace in UAE.
environment: 
  sdk: '>=2.18.1 <3.0.0'
dependencies: 
  animation_wrappers: ^3.0.0
  another_flushbar: ^1.12.29
  carousel_slider: ^4.2.1
  country_picker: ^2.0.20
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  dropdown_button2: ^1.9.2
  favorite_button: ^0.0.4
  flutter: 
    sdk: flutter
  flutter_bloc: ^7.3.3
  flutter_dotenv: ^5.0.2
  flutter_stripe: ^9.0.0
  flutter_svg: ^1.1.6
  font_awesome_flutter: ^10.4.0
  freezed_annotation: ^2.2.0
  get_it: ^7.2.0
  getwidget: ^3.0.1
  google_maps_flutter: ^2.2.3
  grouped_list: ^5.1.2
  http: ^0.13.5
  injectable: ^2.1.0
  intl: ^0.18.0
  multi_select_flutter: ^4.1.3
  onesignal_flutter: ^3.5.1
  pull_to_refresh: ^2.0.0
  shared_preferences: ^2.0.15
  syncfusion_flutter_datepicker: ^20.4.51
  
dev_dependencies: 
  build_runner: ^2.3.3
  freezed: ^2.3.2
  injectable_generator: ^2.1.3
  lint: ^2.0.1
  pubspec_dependency_sorter: ^1.0.3
dependency_overrides: 
  font_awesome_flutter: 
    path: assets/packages/font_awesome_flutter
flutter: 
  assets: 
    - assets/images/logo/
    - assets/images/icons/
    - assets/images/icons/car_features/
    - assets/images/icons/auto/
    - assets/images/icons/car_brands/
    - assets/images/icons/car_categories/
    - assets/images/images/
    - .env
  fonts: 
    - 
      family: Comfortaa
      fonts: 
        - 
          asset: assets/fonts/Comfortaa.ttf
    - 
      family: Open Sans
      fonts: 
        - 
          asset: assets/fonts/OpenSans-Light.ttf
    - 
      family: Poppins
      fonts: 
        - 
          asset: assets/fonts/Poppins-Bold.ttf
  uses-material-design: true
