name: rentop
description: car rental marketplace in UAE.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.18.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_svg: ^1.1.6
  flutter_native_splash: ^2.2.16
  getwidget: ^3.0.1
  freezed_annotation: ^2.2.0
  dartz: ^0.10.1
  go_router: ^6.0.0
  injectable: ^2.1.0
  flutter_dotenv: ^5.0.2
  http: ^0.13.5
  flutter_bloc: ^7.3.3
  get_it: ^7.2.0
  shared_preferences: ^2.0.15
  another_flushbar: ^1.12.29
  persistent_bottom_nav_bar: ^5.0.2
  fluid_bottom_nav_bar: ^1.4.0

dev_dependencies:
  build_runner: ^2.3.3
  freezed: ^2.3.2
  injectable_generator: ^2.1.3
  lint: ^2.0.1

flutter:
  
  uses-material-design: true

  assets:
    - assets/images/logo/
    - assets/images/icons/
    - assets/images/images/
    - .env

  fonts:
    - family: Comfortaa
      fonts:
        - asset: assets/fonts/Comfortaa.ttf

flutter_native_splash:
  color: "#FFFFFF"
  image: assets/images/logo/logo.png
  android: true
  ios: true